spring.datasource.url=jdbc:postgresql://localhost:54320/kuzyaSocialNetwork
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml